### ISSUE TITLE
Dotaz: řešíte nějak connection timeout?

### ISSUE THREAD

**Issue by tvape** [ondrejnov/eet#13]
Zdravím, 

mám dotaz, jestli někdo nějak řešíte connection timeout, neboli jak dlouho čekáte na vrácení FIK?

Pracovně jsem si nastavil 10 sekund, neboť jsem někde četl, že by odpověď měla přijít max do 3 sekund.
Jinak jsem to zatím vyřešil pomocí ini_set('default_socket_timeout', 10) před voláním Dispatcher::send(). Přepokládám, že je to lepší než nastavovat 'connection_timeout' v konstruktoru třídy SoapClient?

Předem díky moc za odpověď.

**Comment by tvape** [comment]
Update: co se týče nastavení limitu, tak funguje pouze ini_set('default_socket_timeout', xxx). Otestováno. 

Pokud se nenastaví, bude klient čekat 60 sekund (což je výchozí hodnota v PHP.ini, pokud nemáte nastaveno jinak). Což je z pohledu pokladního nesmyslně dlouhá doba.

**Comment by adyba** [comment]
Vzhledem k tomu ze se v podstate jedna o velikou synchronni aplikaci, tak kdyz se v podvecer zapnou vsechny kasy ve vsech Kauflandech a Tescach nebude minuta daleko od pravdy ;)

**Comment by tvape** [comment]
Tak nakonec nastavím 3-5 sekund pro pokladní transakce a případně delší pro transakce na pozadí (opětovné zaslání účtenky).
