### ISSUE TITLE
EET Request processing: Unknown service URI was used: /eet/services/EETServiceSOAP/v2 (from client)

### ISSUE THREAD

**Issue by BadChoice** [ondrejnov/eet#14]
<img width="898" alt="captura de pantalla 2016-10-24 a les 10 31 10" src="https://cloud.githubusercontent.com/assets/93900/19638629/144fc354-99d5-11e6-8bbf-1350cba51b7a.png">

I got this error, any idea?

**Comment by ondrejnov** [comment]
actual playground service endpoint is https://pg.eet.cz:443/eet/services/EETServiceSOAP/v3
v2 is not working
