### ISSUE TITLE
RobRichards namespace

### ISSUE THREAD

**Issue by JKoty** [ondrejnov/eet#15]
Přidávám knihovnu do nette frameworku 2.4, ale i při načtení přes vygenerovaný autoload.php mi php narazí na chybějící reference u souborů ze závislých knihoven robrichards/*

Tedy například v `Dispatcher.php` jsem musel změnit
`$objKey = new \XMLSecurityKey(\XMLSecurityKey::RSA_SHA256, ['type' => 'private']);`
na `$objKey = new XMLSecurityKey(XMLSecurityKey::RSA_SHA256, ['type' => 'private']);`
a přidat
`use RobRichards\XMLSecLibs\XMLSecurityKey;`
aby mi to fungovalo, ale měnit knihovnu se mi samozřejmě nechce.

Co dělám špatně?

**Comment by ondrejnov** [comment]
vysla nova verze robrichards/wse-php, ktera zavadi namespace, predchozi byla bez NS.
v composeru je pro robrichards/wse-php hvezdicka, takze se to tim rozbilo

**Comment by ondrejnov** [comment]
vyřešeno ve verzi 0.2

**Comment by PaznerA** [comment]
Zdravím, mám podobný problém. Používám knihovnu v CodeIgniteru a také se mi nedaří načíst závislosti.
Při volání fce **getCheckCodes** se mi zobrazí:

```
Message: Class 'RobRichards\XMLSecLibs\XMLSecurityKey' not found
Filename: application/vendor/ondrejnov/eet/src/Dispatcher.php
```

Do controlleru, který knihovnu volá jsem i přidal:

```
use Ondrejnov\EET\Dispatcher;
use Ondrejnov\EET\Receipt;
use Ondrejnov\EET\Exceptions\ClientException;
use Ondrejnov\EET\Exceptions\RequirementsException;
use Ondrejnov\EET\Exceptions\ServerException;
use Ondrejnov\EET\SoapClient;
use Ondrejnov\EET\Utils\Format;
use RobRichards\XMLSecLibs\XMLSecurityKey;
```

Nevíte, jak to napravit?
