### ISSUE TITLE
like magic methods

### ISSUE THREAD

**Issue by applibs** [ondrejnov/eet#20]
Prosim o upraveni nazvoslovi kvuli warningu v IDE editoru:
"Only magic methods should start with '__'"

U funkci: __doRequest, __getLastResponseTime, __getLastRequest

Diky za pochopeni.

**Comment by janlanger** [comment]
to jsou poděděné metody SoapClienta http://php.net/manual/en/class.soapclient.php upravte si nastavení editoru :-)

**Comment by applibs** [comment]
OK, diky.
