### ISSUE TITLE
Formát PKP

### ISSUE THREAD

**Issue by PaznerA** [ondrejnov/eet#22]
Jaký je správný způsob získání PKP na účtenku?
Funkcí get_checkCodes v poli pkp získám hodnoty:
```
["digest"]=> string(6) "SHA256" 
["cipher"]=> string(7) "RSA2048" 
["encoding"]=> string(6) "base64"
["_"]=> string(256) "� <�� �q J�sv�H��Q.....
```
Na účtence se ovšem má PKP objevit v čitelnější formě než je tato.
Poradíte prosím, jak mám kód decryptovat do správné formy jako je zde:
[https://cdn.i0.cz/public-data/d8/7f/74c2d0143d5db19f32ab44a99583_r16:9_w640_h360_gf3189de2b8aa11e6871b0025900fea04.png?hash=c83032cfd51362a2b96a6b02cfc1064a](url)

**Comment by Pomezny** [comment]
base64_encode()

**Comment by Smurv** [comment]
Vrtá mi hlavou jedna věc: ve zdrojáku jsem nikde nenašel, že by se nad PKP udělal base64_encode(). Udělá se nějak automaticky při vytváření XML? Ve specifikaci přece je, že PKP má být poslán jako base64_encode() a ne jako surová data. A přesto mi FU vesele vrací FIK. Jsem z toho zkrátka jelen :-(

**Comment by demontefacto** [comment]
Dela to ta druha knihovna xmlseclibs.

**Comment by Smurv** [comment]
Díky moc, ale stejně se mi nepodařilo odhalit princip :-( Asi mám nějak špatně nastavený debuger, protože mi to skočí z "processData" v Dispatcher.php rovnou na "__doRequest" v SoapClient.php. Přičemž "processData" posílá jako parametr pole, zatímco "__doRequest" už má jako parametr XML, kde je PKP v Base64... 

Každopádně děkuji, jak budu mít čas, tak to zkusím ještě projít, abych se něco naučil.
