### ISSUE TITLE
Nové certifikáty

### ISSUE THREAD

**Issue by hrasekj** [ondrejnov/eet#24]
Od 6.1.2017 je pro testování ukončena podpora dočasné certifikační autority "CA PG" (CN = GFR EET test CA 1) a je zavedena nová certifikační autorita  "EET CA1 Playground" (CN= ET CA 1 Playground). Bylo by možné vygenerovat nové certifikáty nebo zde popsat postup jak je z crt a p12. Toto je pro mě velká neznámá.

Více info zde: http://www.etrzby.cz/cs/oznameni-k-testovacimu-prostredi-playground

**Comment by demontefacto** [comment]
certifikát ve formátu p12 lze zkonvertovat pomocí openssl
openssl pkcs12 -in cert.p12 -nocerts -out eet.key
openssl pkcs12 -in cert.p12 -clcerts -nokeys -out pure_eet.pem
openssl rsa -in pure_eet.pem -out eet.pem

openssl existuje i pro windows

**Comment by scrazzy** [comment]
Ahoj, nemuzu na to prijit, ale pri poslednim prikazu `openssl rsa -in pure_eet.pem -out eet.pem` mi to hlasi

> 140702239188632:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: ANY PRIVATE KEY

**EDIT**
dalsi problem byl, ze .key soubor byl prazdny. podarilo se mi to rozchodit pomoci pridani parametru -nodes. prikaz openssl rsa jsem z vyse uvedeneho duvodu nepouzil, jen tyto dva:

openssl pkcs12 -in EET_CA1_Playground-CZ00000019.p12 -nocerts -nodes -out eet.key
openssl pkcs12 -in EET_CA1_Playground-CZ00000019.p12 -clcerts -nokeys -out eet.pem

tyto dva vytvorene soubory uz funguji

**Comment by demontefacto** [comment]
omlouvam se za mystifikaci
openssl pkcs12 -in EET_CA1_Playground-CZ1212121218.p12 -out eet_pure.key -nocerts -nodes
openssl pkcs12 -in EET_CA1_Playground-CZ1212121218.p12 -out eet.pem -clcerts -nokeys
openssl rsa -in eet_pure.key -out eet.key

Snad uz to bude spravne. Kazdopadne bez posledniho kroku knihovna .key nesebere

**Comment by scrazzy** [comment]
> openssl pkcs12 -in EET_CA1_Playground-CZ1212121218.p12 -out eet_pure.key -nocerts -nodes
> openssl pkcs12 -in EET_CA1_Playground-CZ1212121218.p12 -out eet.pem -clcerts -nokeys
> openssl rsa -in eet_pure.key -out eet.key

Potvrzuji, ze tyto prikazy funguji spravne, diky.
Nicmene otestoval jsem, ze knihovna pracuje spravne i primo s `eet_pure.key` staci jej prejmenovat na `eet.key`. Jeste dodam pro ostatni aby usetrili google, ze heslo k certifikatum je `eet`.

**Comment by cjayyy** [comment]
Můžete sem prosím někdo hodit ty extrahovaný certifikáty ke stažení? (Případně je forknout do adresáře _certs?)

**Comment by MichalSchwarz** [comment]
Nevim jake budete mit workflow, ale pokud budete od uzivatele chtit PKCS12(.p12) certifikat, v php jej pak snadno extrahujete jako:
```php
/**
 * Prevede p12 soubor na verejny a privatni klic
 * @param string $p12file_uri
 * @param string $password
 * @return array [cert, pkey]
 */
public static function get_certs_from_p12($p12file_uri, $password)
{
  $certs = array();
  $pkcs12 = file_get_contents($p12file_uri);
  openssl_pkcs12_read($pkcs12, $certs, $password);
  $error = openssl_error_string();
  if($error)
  {
    throw new \Exception("Nepodarilo se nacist certifikat: ". $error);
  }
  return $certs;
}
```

**Comment by scrazzy** [comment]
[cert_v3.1.zip](https://github.com/ondrejnov/eet/files/711193/cert_v3.1.zip)

Zde jsou extrahovane nove certifikaty.

**Comment by lebeda** [comment]
Dneska jsem se tím taky zabýval. Už nové certifikáty taky mám, ale nebylo by možné je přidat do repozitáře?

**Comment by ondrejnov** [comment]
certifikát v repozitáři aktualizován
