### ISSUE TITLE
PHP version requirement

### ISSUE THREAD

**Issue by dkellner** [ondrejnov/eet#29]
Is there a specific reason why PHP >=5.6.0 is required? I just tried running the tests with PHP 5.5.38 and encountered no problems so far. And all dependencies (robrichards/xmlseclibs, robrichards/wse-php, nette/tester) require just PHP 5.3.

Right now this requirement prevents installing the library via composer on systems running PHP <5.6.0.

**Comment by renekliment** [comment]
@dkellner I personally don't know about the code, but PHP <=5.5 is no longer maintained - not even security fixes (see [Supported Versions](http://php.net/supported-versions.php)) and there are nice things in PHP >= 5.6. You can install PHP >= 5.6 even on LTS Linux distros, therefore there is no reason to even bother supporting the old version.

**Comment by dkellner** [comment]
@renekliment I was not aware of this for PHP 5.5 - thank you for providing the link to official php documentation! I will close this now as the only reasonable solution is to upgrade.
