### ISSUE TITLE
Formát dat_odesl není ISO 8601?

### ISSUE THREAD

**Issue by HarrierCZ** [ondrejnov/eet#32]
`			'dat_odesl' => time(),`
Neměl by být [dat_odesl](https://github.com/ondrejnov/eet/blob/9296a3e398582631a2519ff8f618f501b761db0f/src/Dispatcher.php#L236) ISO 8601 místo  unix timestamp?

viz [popis rozhraní](http://www.etrzby.cz/assets/cs/prilohy/EET_popis_rozhrani_v3.1.1.pdf)  (bod 3.3.3.2)

**Comment by ondrejnov** [comment]
soap client převede timestamp na základě xsd schematu https://github.com/ondrejnov/eet/blob/master/src/Schema/EETXMLSchema.xsd#L120

**Comment by HarrierCZ** [comment]
Díky se soap dělám poprvé 👍
