### ISSUE TITLE
Nový certifikát

### ISSUE THREAD

**Issue by demontefacto** [ondrejnov/eet#47]
Kvůli nedůvěryhodnosti stávající certifikační autority mění GFŘ vydavatele. Může mě,  prosím, někdo "nakopnout", co s novým certifikátem? Stačí jej "nainstalovat" do systemu nebo je nějakým způsobem součástí této knihovny?
Děkuji

**Comment by MichalSchwarz** [comment]
Součástí knihovny není. 

Jak píšou v oznámení pro PG: `Jde o certifikát, kterým je zabezpečeno spojení na https://pg.eet.cz na HTTPS úrovni`. Takže když se PHP připojuje přes SOAP k serveru eet, dostane nový certifikát. Pokud Vám PHP běží na updatovaném OS, bude vše ok. Samozřejmě je možné root certifikát nainstalovat přímo do OS případně jen do PHP.

Otestovat je možno na playgroundu https://pg.eet.cz, kde už nový certifikát běží od 24. 4. 2018.
