### ISSUE TITLE
Hlášení neprošlo kontrolou Finančního úřadu

### ISSUE THREAD

**Issue by MichalSchwarz** [ondrejnov/eet#48]
Jeden z našich klientů neprošel kontrolou FÚ s výsledkem:

> Na základě kontroly EET v provozovně ... byla v okamžiku placení vystavená účtenka na celkovou částku ...
> 
> Dnes jsem ověřila na daňovém portálu účtenku, tržba byla zaevidována. Rozsah zasílaných údajů nebyl v souladu s ustanovením § 19 ZoET. V datové zprávě o evidované tržbě některé položky s nulou, které nejsou k dané tržbě relevantní, tím bylo porušeno ustanovení § 18 odst. 1 písm. a) ve spojení s ustanovením § 19 odst. 2 ZoET.
> 
> V příloze zasílám detail tržby (datovou zprávou zaslanou na FÚ). Všechny uvedené nuly je třeba odstranit, neobsazené řádky zůstanou prázdné.
> 
> Žádám o zjednání nápravy a to nejpozději do 31.1.2019 a nebude přistoupeno k sankci.
> 
> Jakmile bude opraveno, žádám o zaslání jakékoliv kontrolní účtenky, můžete i na 1 Kč. Já vše zkontroluji.
> 
> V případě, že IT technik řekne, že nuly nejdou odstranit, je třeba od něj získat vyjádření, že dané nuly nejdou odstranit.

![image](https://user-images.githubusercontent.com/13832444/51739851-d3120b80-2092-11e9-9ef9-50d586d29a67.png)

Podle mého výkladu manuálu se tam nikde neuvádí, že irelevantní položky ve zprávě být nesmí.
> Položky označené jako povinné musí být vyplněny v každé datové zprávě. Položky označené jako nepovinné musí být vyplněny, pokud jsou k evidované tržbě relevantní (např. plátci DPH musí mít vyplněny položky o DPH, které jsou relevantní k tržbě).

Nesetkal se někdo s něčím podobným?

**Comment by sieberlukas** [comment]
Není tohle vyřešeno v 4c25f4ac40f326a479321667395cd998af17fd92?

**Comment by MichalSchwarz** [comment]
Aha. Už se řešilo v https://github.com/ondrejnov/eet/pull/37 . Díky

**Comment by brablc** [comment]
Ja jenom dodám, že se u nás ozvali asi dvakrát nebo třikrát s podobným problémem - řeší účtenky třeba půl roku staré. Podivné, že je nenapadne podívat se na aktuální účtenky, zda už jsou v pořádku. Ale dobré, je, že po nás zatím nikdy nechtěli, abychom museli účtenky zpětně stornovat a 0 měnit na NULL.
