### ISSUE TITLE
Unable to get local issuer

### ISSUE THREAD

**Issue by michaljanda** [ondrejnov/eet#50]
Dobrý den,
po dlouhé době se snažím doplnit něco do mé aplikace používající tuto knihovnu. Ze nového playground souboru `.p12` jsem vygeneroval `.pem` a `.key`  nicméně na localhostu (ve win - wamp) stále dostávám chybu `SSL certificate problem: unable to get local issuer certificate`. 
Můžete mi poradit kde je chyba a přibližně jak postupovat? 

Na produkci mi bude také brzo končit platnost, bude i tam potřeba dělat nějaký změny krom výměny pem a key?

Díky moc za každou radu!

**Comment by demontefacto** [comment]
Nová verze, tuším, už podporuje přímo p12 verzi certifikátu, tudíž nebylo potřeba rozdělení. Měl jsem s tím také potíže a nejsem si jist, jestli to nebylo špatným umístěním souborů nebo tím, že jsem z certifikátu šaptně extrahoval klíč

**Comment by ondrejnov** [comment]
https://github.com/ondrejnov/eet/issues/39

**Comment by michaljanda** [comment]
Diky, pardon měl jsem lépe hledat
