### ISSUE TITLE
Throwing soap exception from yesterday /03.08.2016/

### ISSUE THREAD

**Issue by pitrrs** [ondrejnov/eet#6]
Hi,

when retrieving the FIK code i getting response:
`{"faultstring":"Could not connect to host","faultcode":"HTTP"}`

Throwed in:
ondrejnov/eet/src/SoapClient.php line 62

Endpoint changed? On EET portal (eltrzby.cz) is no information about this changes.

**EDIT**: Yesterday we also upgrading PHP to 5.6.4 ==> this is the problem

**Comment by ondrejnov** [comment]
I just tested PHP 5.6.17 and 7.0.6 (Debian OS). 
Everything is OK for me, without connection problem.

**Comment by nickmetal** [comment]
I have the same problem on Linux Mint x64, php -v ->  5.6.23
Is this example which is located in readme file is still working?
