### ISSUE TITLE
Composer install - dependency 

### ISSUE THREAD

**Issue by littlewall** [ondrejnov/eet#8]
Zdravím,
dělá mi problém instalace přes Composer.

![composer-eet](https://cloud.githubusercontent.com/assets/16668308/18870046/3f4cd3a2-84af-11e6-9559-2e283eb16ff3.png)

Nejde mi ani nainstalovat samotný `robrichards/wse-php`

Děkuji předem za nápad či postrčení.
Milan Zítka

**Comment by ondrejnov** [comment]
wse-php neni stable, ale jen dev. Tusim, ze jsem u projektu nastavoval 
minimum stability na dev, aby to slo

**Comment by janlanger** [comment]
robrichards/wse-php má 5 dní starou verzi 2.0, ta by jako requirment nestačila?

**Comment by ondrejnov** [comment]
aktualizoval jsem závislosti na nové robrichards/wse-php
